app:
  name: "web_app"
  mode: "dev"
  port:
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: ""
  port:
  user: ""
  password: ""
  dbname: ""
  max_open_connections: 200
  max_idle_connections: 100
redis:
  host: ""
  port:
  password: ""
  db: 0
  pool_size: 100
